### ISSUE TITLE
Error detected while processing  function 101

### ISSUE THREAD

**Issue by alesandar** [francoiscabrol/ranger.vim#5] opened 2016-03-27 22:07 UTC
When opening a new file, I get the following error:

```
Error detected while processing function 101..<SNR>30_Bclose:
line   45:
E516: No buffers were deleted: bdelete! 6
```
The file is successfully loaded afterwards. In that case, don't you think that the error message must be suppressed if everything went fine? I'm using Neovim 0.1.2.

**Comment by alesandar** [comment] 2016-03-27 22:21
I've just noticed that the repository here is a fork.
Mizuchi's version works like a charm (without the necessity of bclose).

**Comment by francoiscabrol** [comment] 2016-03-29 14:19
it is not a fork... but yes the message could be improve. I use Bclose to fix a bug while working with several panes (windows) with neovim. I am going to try Mizuchi's version to see what's the behaviours. thanks for the link, I think its repo didn't exist when I've created this one.

**Comment by francoiscabrol** [comment] 2016-03-29 14:21
Bclose is a small function, I could just implemented it directly in the ranger.vim code.

**Comment by alesandar** [comment] 2016-03-30 07:52
Excuse me for the mistake. I believe that the issue isn't 100% reproducible.
By the way, I've already had bclose installed when that happened for first time.

**Comment by francoiscabrol** [comment] 2016-05-28 15:54
It seems that installing Bclose is a problem for several persons so iam going to integrate its code directly in Ranger

**Comment by francoiscabrol** [comment] 2016-10-03 14:32
I close the issue since this error is not reproducible.

**Comment by waiting-for-dev** [comment] 2016-10-06 16:07
Hey,

I can reproduce the issue. If I install Bclose and ranger.vim, the second time I open a file with ranger the error appears.

**Comment by francoiscabrol** [comment] 2016-10-07 00:37
Hum ok it's weird, I have never seen that on my machine... which vim version do you use?

**Comment by waiting-for-dev** [comment] 2016-10-07 16:17
I'm using neovim 0.1.5.

I tried to disable the rest of plugins to check if it was some kind of incompatibility issue but the error persists.

Please, tell me if you need any other debug information.

Thanks.

**Comment by francoiscabrol** [comment] 2016-10-08 21:08
I tried with the neovim 0.1.5 but I can't reproduce it... I reopen the issue. I think the problem is more related to Bclose. vim-bbye is equivalent to Bclose and had the same bug: https://github.com/moll/vim-bbye/issues/5.
Since it is fixed for vim-bbye, we could use this one instead. Or maybe we could call Bclose in a way allowing to catch and hide the error...

**Closed** 2016-10-08 21:10 UTC

**Comment by francoiscabrol** [comment] 2016-10-08 21:13
Ok I reproduced the error by using Bclose on Startify. Now I run Bclose with silent since the behaviours seems to be the same. The error is just hidden and everything seems to work.

**Comment by waiting-for-dev** [comment] 2016-10-10 08:26
Thanks! Effectively,  now it doesn't show any error and it seems to work without troubles. Thank you very much for your quick support.
